/**
 * It represents a button which opens a survey in a new tab with the
 * {@link FeedbackButton._SURVEY_ID} that is generated by Hotjar whenever a
 * new survey has been created.
 */
class FeedbackButton extends MainModalHeaderElement {

    static _SURVEY_ID = "155683";

    constructor() {
        super("#feedbackHeaderButton")
    }

    onClick(event) {
        const url = 'https://surveys.hotjar.com/s?siteId=711902&surveyId=' + FeedbackButton._SURVEY_ID;
        ContentServices.analyticsTracker.trackUsageEvent(ANALYTICS_ACTION.MAIN_MODAL_HEADER, "feedback");
        window.open(url, '_blank');
    }
}
